sudo: required

language: php
php:
  - 7.3.9

services:
  - docker

addons:
  chrome: stable

before_install:
  - nvm install 12.10.0
  - node -v
  - npm -v

before_script:
  - cp .env-dist .env
  - export $(cat .env | sed -e /^$/d -e /^#/d | xargs)
  - env
  - docker-compose up -d --build
  - docker ps -a
  - MYSQL_PORT=3308 && MYSQL_HOST=127.0.0.1
  - while [[ "$(curl -o /dev/null -Isw '%{http_code}\n' http://localhost/api/ping)" -ne 200 ]]; do sleep 3; echo "Waiting API to be available..."; done
  - while ! docker exec mysql mysql -u"$MYSQL_USERNAME" -p"$MYSQL_PASSWORD" -e "select 1" > /dev/null 2>&1; do sleep 3; echo "Waiting MYSQL to be available..."; done
  - docker logs api
  - cd api
  - composer install
  - cd ..
  - cd backend
  - npm install
  - cd ..
  - cd frontend
  - npm install
  - cd ..

script:
  - cd api
  - composer run sniff  
  - composer run test:unit
  - composer run test:functional
  - cd ..
  - cd frontend
  - npm run lint
  - npm run test
  # - npm run e2e # Temporary disable as travis not supporting latest chrome
  - cd ..
  - cd backend
  - npm run lint
  - npm run test
  - cd ..

after_script:
  - docker-compose down -v

notifications:
  email: false
